# Generated by Django 4.1.5 on 2023-01-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estadia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pago',
            field=models.IntegerField(),
        ),
    ]
