# Generated by Django 4.1.5 on 2023-01-27 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0002_alter_reserva_estadia_alter_reserva_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='creado',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='fecha_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
