# Generated by Django 4.1.5 on 2023-01-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0003_remove_habitacion_creado_habitacion_fecha_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Debito', 'Debito'), ('Credito', 'Credito'), ('MercadoPago', 'MercadoPago')], max_length=50),
        ),
    ]
