# Generated by Django 4.1.5 on 2023-01-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0004_alter_reserva_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Inahabilitada', 'Inahabilitada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], max_length=50),
        ),
    ]
